#!/bin/sh
# Gradle wrapper script — the actual JAR is generated by `gradle wrapper`
# GitHub Actions uses gradle/actions/setup-gradle which handles this automatically

APP_HOME=$( cd "${APP_HOME:-$(dirname "$0")}" > /dev/null && pwd -P )
APP_NAME="Gradle"
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use
if [ -n "$JAVA_HOME" ] ; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD="java"
fi

exec "$JAVACMD" ${DEFAULT_JVM_OPTS} ${JAVA_OPTS} ${GRADLE_OPTS} \
    "-Dorg.gradle.appname=$APP_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain "$@"
